Visual Studio Code (1.78.0, undefined, desktop)
Jupyter Extension Version: 2023.4.1001091014.
Python Extension Version: 2023.8.0.
Platform: linux (x64).
Workspace folder ~/study/python/lab, Home = /home/_wajs_err_
22:12:07.312 [info] ZMQ loaded without the fallback mechanism.
22:12:07.547 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
22:12:07.548 [info] Start refreshing Kernel Picker (1683486727548)
22:12:07.553 [info] Using Pylance
22:12:07.709 [debug] No controller, hence notebook communications cannot be initialized for editor ~/study/python/lab/lab.ipynb
22:12:07.874 [debug] Get Custom Env Variables, Class name = wc, completed in 327ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:12:07.874 [debug] Jupyter Paths /kernels: 
22:12:07.877 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
22:12:07.884 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:12:07.884 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
22:12:07.887 [debug] Get Custom Env Variables, Class name = wc, completed in 3ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
22:12:07.908 [debug] Not Searching for kernels as path does not exist, /usr/share/jupyter/kernels
22:12:07.909 [debug] Not Searching for kernels as path does not exist, /usr/local/share/jupyter/kernels
22:12:07.989 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json for 
22:12:07.991 [debug] Conda file returned by Python Extension is conda
22:12:08.052 [warn] Failed to get activated env vars for /bin/python in 168ms
22:12:08.053 [debug] Create ProcessService, Class name = nc (started execution), Arg 1: undefined
22:12:08.053 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
22:12:08.056 [debug] Get Custom Env Variables, Class name = wc, completed in 3ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
22:12:08.056 [debug] Create ProcessService, Class name = nc, completed in 3ms, has a truthy return value, Arg 1: undefined
22:12:08.069 [info] Process Execution: /bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
22:12:08.112 [debug] USER_SITE for /bin/python is ~/.local/bin
22:12:08.113 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
22:12:08.113 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:12:08.113 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:12:08.113 [debug] Got env vars with python /bin/python in 229ms with 46 variables
22:12:08.113 [debug] Getting activated env variables, Class name = Is, completed in 230ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:12:08.125 [info] Process Execution: /bin/python -m pip list
22:12:08.476 [debug] Full interpreter list after refreshing (total 641ms, resolve 36ms, refresh 605ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
22:12:08.481 [debug] Full interpreter list after refreshing (total 2ms, resolve 1ms, refresh 1ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
22:12:08.493 [debug] refreshData after detecting changes to interpreters
22:12:08.493 [debug] Listing Python & non-Python kernels for Interpreter /bin/python
22:12:08.494 [debug] Listing Python & non-Python kernels for Interpreter /sbin/python
22:12:08.494 [debug] Finding Global Python KernelSpecs
22:12:08.495 [debug] refreshData after detecting changes to interpreters
22:12:08.496 [debug] Listing Python & non-Python kernels for Interpreter /usr/bin/python
22:12:08.496 [debug] refreshData after detecting changes to interpreters
22:12:08.496 [debug] Listing Python & non-Python kernels for Interpreter /usr/sbin/python
22:12:08.497 [debug] refreshData after detecting changes to interpreters
22:12:08.498 [debug] refreshData after detecting changes to interpreters
22:12:08.499 [debug] Full interpreter list is length: 4, /bin/python::Unknown:/bin/python, /sbin/python::Unknown:/sbin/python, /usr/bin/python::Unknown:/usr/bin/python, /usr/sbin/python::Unknown:/usr/sbin/python
22:12:08.499 [debug] Refreshed Environments
22:12:08.525 [debug] Kernel for interpreter /bin/python is .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:12:08.525 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:12:08.529 [debug] Kernel for interpreter /sbin/python is .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
22:12:08.529 [debug] Kernels for interpreter /sbin/python are .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
22:12:08.531 [debug] Kernel for interpreter /usr/bin/python is .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
22:12:08.531 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
22:12:08.533 [debug] Kernel for interpreter /usr/sbin/python is .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
22:12:08.533 [debug] Kernels for interpreter /usr/sbin/python are .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
22:12:08.576 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:12:08.577 [debug] start the kernel, options.disableUI=true for ~/study/python/lab/lab.ipynb
22:12:08.578 [debug] Initialize notebook communications for editor ~/study/python/lab/lab.ipynb
22:12:08.578 [debug] Resolving notebook UI Comms (resolve) for ~/study/python/lab/lab.ipynb
22:12:08.578 [debug] initialize CommonMessageCoordinator
22:12:08.584 [debug] Registering commtarget jupyter.widget
22:12:08.584 [debug] IPyWidgetMessageDispatcher.initialize
22:12:08.585 [debug] Attempting to determine version of IPyWidgets
22:12:08.586 [debug] Controller selection change completed
22:12:08.586 [debug] Waiting for IPyWidgets version
22:12:08.587 [debug] Waiting for IPyWidgets version promise
22:12:08.634 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher  (Python Path: /bin/python, Unknown, 3.10.10) for '~/study/python/lab/lab.ipynb' (disableUI=true)
22:12:08.634 [debug] Creating raw notebook for resource '~/study/python/lab/lab.ipynb'
22:12:08.636 [debug] Kernel Launcher. launch, Class name = Kg (started execution), Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
22:12:08.637 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:12:08.637 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
22:12:08.644 [debug] Get Custom Env Variables, Class name = wc, completed in 7ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
22:12:08.658 [debug] Launching kernel in kernelProcess.ts, Class name = Ug (started execution), Arg 1: "~/study/python/lab", Arg 2: ""
22:12:08.682 [warn] Failed to get activated env vars for /bin/python in 45ms
22:12:08.683 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
22:12:08.683 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:12:08.683 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:12:08.683 [debug] Got env vars with python /bin/python in 46ms with 46 variables
22:12:08.683 [debug] Getting activated env variables, Class name = Is, completed in 46ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:12:08.700 [info] Process Execution: /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:12:08.700 [debug] Kernel Env Variables for ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/jupyter/kernels/pythonjvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a/kernel.json, PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
22:12:08.713 [info] Process Execution: /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"1b46d24d-0900-48a7-9fe4-b0154adcc9c0" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-5837631e25vPxycw4w.json
    > cwd: ~/study/python/lab
22:12:08.713 [debug] Launching kernel in kernelProcess.ts, Class name = Ug, completed in 55ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: ""
22:12:09.010 [info] ipykernel version & path 6.22.0, ~/.local/lib/python3.10/site-packages/ipykernel/__init__.py for /bin/python
22:12:09.486 [debug] KernelProcess error: ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1b46d24d-0900-48a7-9fe4-b0154adcc9c0' instead of 'b"1b46d24d-0900-48a7-9fe4-b0154adcc9c0"'.
  warn(

22:12:09.497 [debug] KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-5837631e25vPxycw4w.json

22:12:09.498 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-5837631e25vPxycw4w.json

22:12:09.500 [info] End refreshing Kernel Picker (1683486727548)
22:12:09.555 [debug] Kernel Launcher. launch, Class name = Kg, completed in 918ms, has a truthy return value, Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
22:12:09.565 [info] ZMQ loaded without the fallback mechanism.
22:12:09.571 [debug] Waiting for Raw Session to be ready in postStartRawSession
22:12:09.571 [debug] Waiting for Raw session to be ready, currently connected
22:12:09.571 [debug] Raw session connected
22:12:09.572 [debug] Waiting for Raw session to be ready for 30s
22:12:09.572 [debug] Waited for Raw session to be ready & got connected
22:12:09.572 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
22:12:09.572 [debug] Kernel status before requesting kernel info and after ready is unknown
22:12:09.572 [debug] Sending request for kernelinfo
22:12:09.582 [debug] Got response for requestKernelInfo
22:12:09.583 [debug] Successfully compelted postStartRawSession
22:12:09.583 [info] Started Kernel Python 3.10.10 (pid: 583923)
22:12:09.584 [info] Started new session 4f56b042-376b-44d0-ac79-a2cddc0dd43b
22:12:09.585 [debug] Started running kernel initialization for ~/study/python/lab/lab.ipynb
22:12:09.587 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
22:12:09.700 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
22:12:09.700 [debug] Determined IPyKernel Version as 8 and event fired
22:12:09.700 [debug] Version of IPyWidgets 8 determined after 1.116s
22:12:09.721 [debug] Initialize matplotlib for ~/study/python/lab/lab.ipynb
22:12:09.721 [debug] Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD
22:12:10.240 [debug] Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD with 1 output(s)
22:12:10.240 [debug] Requesting Kernel info
22:12:10.241 [debug] Got Kernel info
22:12:10.241 [debug] End running kernel initialization, now waiting for idle
22:12:10.241 [debug] Waiting for 60000ms idle on (kernel): 4f56b042-376b-44d0-ac79-a2cddc0dd43b -> idle
22:12:10.241 [debug] Finished waiting for idle on (kernel): 4f56b042-376b-44d0-ac79-a2cddc0dd43b -> idle
22:12:10.241 [debug] End running kernel initialization, session is idle
22:12:10.244 [debug] IPyWidgetScriptSource.initialize
22:12:10.245 [debug] IPyWidgetMessageDispatcher.initialize
22:12:10.246 [debug] getDataDirsImpl, Class name = nh (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
22:12:10.246 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
22:12:10.247 [debug] Get Custom Env Variables, Class name = wc, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:12:10.247 [debug] Jupyter Paths : 
22:12:10.264 [info] Process Execution: /bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/pythonFiles/printJupyterDataDir.py
22:12:10.294 [debug] IPyWidgetMessageDispatcher.initialize
22:12:10.294 [debug] Web view is ready to receive widget messages
22:12:10.307 [debug] getDataDirsImpl, Class name = nh, completed in 61ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
22:12:10.372 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
22:12:10.373 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
22:12:10.377 [debug] IPyWidgetMessageDispatcher.initialize
22:12:10.377 [debug] IPyWidgetMessageDispatcher.initialize
22:12:10.381 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
22:12:10.382 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
22:12:10.382 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/scripts/5025d6a5c4df71f4502a853d7f80a37d8be0228745293b0e528bc4850f83a169/jupyter
22:12:10.383 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/scripts/5025d6a5c4df71f4502a853d7f80a37d8be0228745293b0e528bc4850f83a169/jupyter
22:12:23.536 [debug] Updating cache with Python kernels startUsingPythonInterpreter:'.jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (interpreter id = /bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (interpreter id = /sbin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (interpreter id = /usr/bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Added = startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Updated = , Removed = 
22:16:42.793 [info] Shutting down notebooks for ea289c75-9531-4b51-805c-5fe482ddbf46
22:16:42.793 [info] Disposing HostJupyterExecution 663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.793 [debug] Disposing super HostJupyterExecution 663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.793 [info] Dispose Kernel '~/study/python/lab/lab.ipynb' associated with '~/study/python/lab/lab.ipynb'
22:16:42.797 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224370
	at jm.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224579)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770348
	at Array.map (<anonymous>)
	at va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770338)
	at Module.FE (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:590356)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:10974)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
22:16:42.798 [debug] shutdownSession 4f56b042-376b-44d0-ac79-a2cddc0dd43b, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
22:16:42.798 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:16:42.799 [info] Dispose Kernel process 583923.
22:16:42.817 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/study/python/lab/lab.ipynb
22:16:42.818 [info] Disposing HostJupyterExecution 663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.818 [debug] Finished disposing HostJupyterExecution  663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.822 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher and documents file://~/study/python/lab/lab.ipynb
22:16:42.822 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
22:16:42.822 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
22:16:42.823 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
22:16:42.823 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
22:16:42.823 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
22:16:42.823 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
22:16:42.823 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
22:16:42.825 [debug] Cleaning up server cache 663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.827 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121414
	at Array.map (<anonymous>)
	at av.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121404)
	at async Promise.all (index 0)
	at async va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770360)
	at async Promise.all (index 12)
	at async v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9171)
22:16:42.827 [debug] shutdownSession 4f56b042-376b-44d0-ac79-a2cddc0dd43b, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
22:16:42.827 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:16:42.828 [debug] Finished disposing HostJupyterExecution  663983d8-9210-4644-be5b-5ddaf1ae1037
22:16:42.834 [debug] Disposed Kernel process 583923.
22:16:42.834 [debug] shutdownSession 4f56b042-376b-44d0-ac79-a2cddc0dd43b, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
22:16:42.834 [debug] shutdownSession 4f56b042-376b-44d0-ac79-a2cddc0dd43b, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
22:16:42.834 [debug] Shutdown session - get restart session
22:16:42.834 [debug] Shutdown session -- complete
22:16:42.835 [debug] Shutdown session - get restart session
22:16:42.835 [debug] Shutdown session -- complete
22:16:42.835 [warn] Failed to delete connection file ~/.local/share/jupyter/runtime/kernel-v2-5837631e25vPxycw4w.json for pid 583923 [Canceled (FileSystemError): Canceled
	at Zt.c (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:27273)
	at Object.stat (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:25374)
	at async _d.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:18527)
	at async ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:89152] {
  code: 'Unknown'
}
