Visual Studio Code (1.78.0, undefined, desktop)
Jupyter Extension Version: 2023.4.1001091014.
Python Extension Version: 2023.8.0.
Platform: linux (x64).
Workspace folder ~/study/python/lab, Home = /home/_wajs_err_
01:40:42.644 [info] ZMQ loaded without the fallback mechanism.
01:40:42.856 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
01:40:42.857 [info] Start refreshing Kernel Picker (1685227242857)
01:40:42.867 [info] Using Pylance
01:40:43.099 [debug] No controller, hence notebook communications cannot be initialized for editor ~/study/python/lab/lab.ipynb
01:40:43.532 [debug] Get Custom Env Variables, Class name = wc, completed in 676ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
01:40:43.532 [debug] Jupyter Paths /kernels: 
01:40:43.536 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
01:40:43.548 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
01:40:43.548 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
01:40:43.551 [debug] Get Custom Env Variables, Class name = wc, completed in 3ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
01:40:43.573 [debug] Not Searching for kernels as path does not exist, /usr/share/jupyter/kernels
01:40:43.574 [debug] Not Searching for kernels as path does not exist, /usr/local/share/jupyter/kernels
01:40:43.660 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json for 
01:40:43.664 [debug] Conda file returned by Python Extension is conda
01:40:43.681 [warn] Failed to get activated env vars for /bin/python in 133ms
01:40:43.682 [debug] Create ProcessService, Class name = nc (started execution), Arg 1: undefined
01:40:43.683 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
01:40:43.694 [debug] Get Custom Env Variables, Class name = wc, completed in 11ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
01:40:43.694 [debug] Create ProcessService, Class name = nc, completed in 12ms, has a truthy return value, Arg 1: undefined
01:40:43.703 [info] Process Execution: /bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
01:40:43.743 [debug] USER_SITE for /bin/python is ~/.local/bin
01:40:43.743 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
01:40:43.743 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
01:40:43.744 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
01:40:43.744 [debug] Got env vars with python /bin/python in 196ms with 46 variables
01:40:43.744 [debug] Getting activated env variables, Class name = Is, completed in 196ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
01:40:43.755 [info] Process Execution: /bin/python -m pip list
01:40:44.018 [debug] Full interpreter list after refreshing (total 524ms, resolve 35ms, refresh 489ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
01:40:44.025 [debug] Full interpreter list after refreshing (total 2ms, resolve 2ms, refresh 0ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
01:40:44.030 [debug] refreshData after detecting changes to interpreters
01:40:44.030 [debug] Listing Python & non-Python kernels for Interpreter /bin/python
01:40:44.031 [debug] Listing Python & non-Python kernels for Interpreter /sbin/python
01:40:44.032 [debug] Finding Global Python KernelSpecs
01:40:44.034 [debug] refreshData after detecting changes to interpreters
01:40:44.034 [debug] Listing Python & non-Python kernels for Interpreter /usr/bin/python
01:40:44.035 [debug] refreshData after detecting changes to interpreters
01:40:44.035 [debug] Listing Python & non-Python kernels for Interpreter /usr/sbin/python
01:40:44.036 [debug] refreshData after detecting changes to interpreters
01:40:44.038 [debug] refreshData after detecting changes to interpreters
01:40:44.039 [debug] Full interpreter list is length: 4, /bin/python::Unknown:/bin/python, /sbin/python::Unknown:/sbin/python, /usr/bin/python::Unknown:/usr/bin/python, /usr/sbin/python::Unknown:/usr/sbin/python
01:40:44.039 [debug] Refreshed Environments
01:40:44.049 [debug] Kernel for interpreter /bin/python is .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
01:40:44.049 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
01:40:44.055 [debug] Kernel for interpreter /sbin/python is .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
01:40:44.055 [debug] Kernels for interpreter /sbin/python are .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
01:40:44.057 [debug] Kernel for interpreter /usr/bin/python is .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
01:40:44.057 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
01:40:44.060 [debug] Kernel for interpreter /usr/sbin/python is .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
01:40:44.060 [debug] Kernels for interpreter /usr/sbin/python are .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
01:40:44.111 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
01:40:44.112 [debug] start the kernel, options.disableUI=true for ~/study/python/lab/lab.ipynb
01:40:44.113 [debug] Initialize notebook communications for editor ~/study/python/lab/lab.ipynb
01:40:44.113 [debug] Resolving notebook UI Comms (resolve) for ~/study/python/lab/lab.ipynb
01:40:44.114 [debug] initialize CommonMessageCoordinator
01:40:44.120 [debug] Registering commtarget jupyter.widget
01:40:44.120 [debug] IPyWidgetMessageDispatcher.initialize
01:40:44.120 [debug] Attempting to determine version of IPyWidgets
01:40:44.121 [debug] Controller selection change completed
01:40:44.122 [debug] Waiting for IPyWidgets version
01:40:44.122 [debug] Waiting for IPyWidgets version promise
01:40:44.157 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher  (Python Path: /bin/python, Unknown, 3.10.10) for '~/study/python/lab/lab.ipynb' (disableUI=true)
01:40:44.158 [debug] Creating raw notebook for resource '~/study/python/lab/lab.ipynb'
01:40:44.172 [debug] Kernel Launcher. launch, Class name = Kg (started execution), Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
01:40:44.172 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
01:40:44.172 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
01:40:44.178 [debug] Get Custom Env Variables, Class name = wc, completed in 6ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
01:40:44.185 [debug] Launching kernel in kernelProcess.ts, Class name = Ug (started execution), Arg 1: "~/study/python/lab", Arg 2: ""
01:40:44.291 [warn] Failed to get activated env vars for /bin/python in 119ms
01:40:44.292 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
01:40:44.292 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
01:40:44.292 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
01:40:44.292 [debug] Got env vars with python /bin/python in 120ms with 46 variables
01:40:44.292 [debug] Getting activated env variables, Class name = Is, completed in 120ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
01:40:44.304 [info] Process Execution: /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
01:40:44.305 [debug] Kernel Env Variables for ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/jupyter/kernels/pythonjvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a/kernel.json, PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
01:40:44.320 [info] Process Execution: /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"6470e72e-aaae-4a3b-9f29-af6a2abf38af" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-43363izgDuXIwqXuX.json
    > cwd: ~/study/python/lab
01:40:44.320 [debug] Launching kernel in kernelProcess.ts, Class name = Ug, completed in 135ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: ""
01:40:44.731 [info] ipykernel version & path 6.22.0, ~/.local/lib/python3.10/site-packages/ipykernel/__init__.py for /bin/python
01:40:45.040 [info] End refreshing Kernel Picker (1685227242857)
01:40:45.468 [debug] KernelProcess error: ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '6470e72e-aaae-4a3b-9f29-af6a2abf38af' instead of 'b"6470e72e-aaae-4a3b-9f29-af6a2abf38af"'.
  warn(

01:40:45.477 [debug] KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-43363izgDuXIwqXuX.json

01:40:45.477 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-43363izgDuXIwqXuX.json

01:40:45.538 [debug] Kernel Launcher. launch, Class name = Kg, completed in 1366ms, has a truthy return value, Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
01:40:45.543 [info] ZMQ loaded without the fallback mechanism.
01:40:45.548 [debug] Waiting for Raw Session to be ready in postStartRawSession
01:40:45.548 [debug] Waiting for Raw session to be ready, currently connected
01:40:45.548 [debug] Raw session connected
01:40:45.548 [debug] Waiting for Raw session to be ready for 30s
01:40:45.548 [debug] Waited for Raw session to be ready & got connected
01:40:45.548 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
01:40:45.548 [debug] Kernel status before requesting kernel info and after ready is unknown
01:40:45.548 [debug] Sending request for kernelinfo
01:40:45.554 [debug] Got response for requestKernelInfo
01:40:45.554 [debug] Successfully compelted postStartRawSession
01:40:45.554 [info] Started Kernel Python 3.10.10 (pid: 43532)
01:40:45.555 [info] Started new session 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6
01:40:45.555 [debug] Started running kernel initialization for ~/study/python/lab/lab.ipynb
01:40:45.556 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
01:40:45.626 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
01:40:45.626 [debug] Determined IPyKernel Version as 8 and event fired
01:40:45.626 [debug] Version of IPyWidgets 8 determined after 1.506s
01:40:45.628 [debug] Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD
01:40:45.636 [debug] Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD with 1 output(s)
01:40:45.637 [debug] Requesting Kernel info
01:40:45.637 [debug] Got Kernel info
01:40:45.637 [debug] End running kernel initialization, now waiting for idle
01:40:45.637 [debug] Waiting for 60000ms idle on (kernel): 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6 -> idle
01:40:45.637 [debug] Finished waiting for idle on (kernel): 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6 -> idle
01:40:45.637 [debug] End running kernel initialization, session is idle
01:40:45.639 [debug] IPyWidgetScriptSource.initialize
01:40:45.639 [debug] IPyWidgetMessageDispatcher.initialize
01:40:45.639 [debug] getDataDirsImpl, Class name = nh (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
01:40:45.639 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
01:40:45.640 [debug] Get Custom Env Variables, Class name = wc, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
01:40:45.640 [debug] Jupyter Paths : 
01:40:45.647 [info] Process Execution: /bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/pythonFiles/printJupyterDataDir.py
01:40:45.670 [debug] getDataDirsImpl, Class name = nh, completed in 31ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
01:40:46.210 [debug] IPyWidgetMessageDispatcher.initialize
01:40:46.210 [debug] Web view is ready to receive widget messages
01:40:46.254 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
01:40:46.255 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
01:40:46.271 [debug] IPyWidgetMessageDispatcher.initialize
01:40:46.271 [debug] IPyWidgetMessageDispatcher.initialize
01:40:46.279 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/scripts/5025d6a5c4df71f4502a853d7f80a37d8be0228745293b0e528bc4850f83a169/jupyter
01:40:46.280 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
01:40:46.280 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
01:40:46.280 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/scripts/5025d6a5c4df71f4502a853d7f80a37d8be0228745293b0e528bc4850f83a169/jupyter
01:40:59.063 [debug] Updating cache with Python kernels startUsingPythonInterpreter:'.jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (interpreter id = /bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (interpreter id = /sbin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (interpreter id = /usr/bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Added = startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Updated = , Removed = 
01:41:02.845 [info] Shutting down notebooks for f7a79ead-b715-4f5a-b9cc-5f06cfdebc00
01:41:02.845 [info] Disposing HostJupyterExecution 7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.845 [debug] Disposing super HostJupyterExecution 7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.846 [info] Dispose Kernel '~/study/python/lab/lab.ipynb' associated with '~/study/python/lab/lab.ipynb'
01:41:02.850 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224370
	at jm.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224579)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770348
	at Array.map (<anonymous>)
	at va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770338)
	at Module.FE (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:590356)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:10974)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
01:41:02.850 [debug] shutdownSession 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
01:41:02.850 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
01:41:02.851 [info] Dispose Kernel process 43532.
01:41:02.862 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/study/python/lab/lab.ipynb
01:41:02.863 [info] Disposing HostJupyterExecution 7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.863 [debug] Finished disposing HostJupyterExecution  7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.865 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher and documents file://~/study/python/lab/lab.ipynb
01:41:02.865 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
01:41:02.865 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
01:41:02.865 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
01:41:02.866 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
01:41:02.866 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
01:41:02.866 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
01:41:02.866 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
01:41:02.867 [debug] Cleaning up server cache 7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.869 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121414
	at Array.map (<anonymous>)
	at av.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121404)
	at async Promise.all (index 0)
	at async va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770360)
	at async Promise.all (index 12)
	at async v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9171)
01:41:02.869 [debug] shutdownSession 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
01:41:02.869 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
01:41:02.869 [debug] Finished disposing HostJupyterExecution  7da51864-c1a6-4270-a466-bfc0cadfb523
01:41:02.876 [debug] KernelProcess Exit Exit - undefined ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '6470e72e-aaae-4a3b-9f29-af6a2abf38af' instead of 'b"6470e72e-aaae-4a3b-9f29-af6a2abf38af"'.
  warn(

01:41:02.879 [debug] Disposed Kernel process 43532.
01:41:02.879 [debug] shutdownSession 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
01:41:02.879 [debug] shutdownSession 365f42b4-69e1-4a87-9e9e-609bb0e4ffd6, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
01:41:02.879 [debug] Shutdown session - get restart session
01:41:02.880 [debug] Shutdown session -- complete
01:41:02.880 [debug] Shutdown session - get restart session
01:41:02.880 [debug] Shutdown session -- complete
01:41:02.881 [warn] Failed to delete connection file ~/.local/share/jupyter/runtime/kernel-v2-43363izgDuXIwqXuX.json for pid 43532 [Canceled (FileSystemError): Canceled
	at Zt.c (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:27273)
	at Object.stat (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:25374)
	at async _d.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:18527)
	at async ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:89152] {
  code: 'Unknown'
}
