Visual Studio Code (1.78.0, undefined, desktop)
Jupyter Extension Version: 2023.4.1001091014.
Python Extension Version: 2023.8.0.
Platform: linux (x64).
Workspace folder ~/study/python/lab, Home = /home/_wajs_err_
22:48:30.696 [info] ZMQ loaded without the fallback mechanism.
22:48:30.951 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
22:48:30.951 [info] Start refreshing Kernel Picker (1683488910951)
22:48:30.956 [info] Using Pylance
22:48:31.161 [debug] No controller, hence notebook communications cannot be initialized for editor ~/study/python/lab/lab.ipynb
22:48:31.619 [debug] Get Custom Env Variables, Class name = wc, completed in 668ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:48:31.619 [debug] Jupyter Paths /kernels: 
22:48:31.623 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
22:48:31.635 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:48:31.635 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
22:48:31.640 [debug] Get Custom Env Variables, Class name = wc, completed in 5ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: "RunPythonCode"
22:48:31.665 [debug] Not Searching for kernels as path does not exist, /usr/share/jupyter/kernels
22:48:31.666 [debug] Not Searching for kernels as path does not exist, /usr/local/share/jupyter/kernels
22:48:31.709 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json for 
22:48:31.710 [debug] Conda file returned by Python Extension is conda
22:48:31.751 [warn] Failed to get activated env vars for /bin/python in 116ms
22:48:31.752 [debug] Create ProcessService, Class name = nc (started execution), Arg 1: undefined
22:48:31.752 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
22:48:31.760 [debug] Get Custom Env Variables, Class name = wc, completed in 8ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
22:48:31.760 [debug] Create ProcessService, Class name = nc, completed in 8ms, has a truthy return value, Arg 1: undefined
22:48:31.772 [info] Process Execution: /bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
22:48:31.828 [debug] USER_SITE for /bin/python is ~/.local/bin
22:48:31.828 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
22:48:31.828 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:48:31.829 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:48:31.829 [debug] Got env vars with python /bin/python in 194ms with 46 variables
22:48:31.829 [debug] Getting activated env variables, Class name = Is, completed in 194ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:48:31.848 [info] Process Execution: /bin/python -m pip list
22:48:32.172 [debug] Full interpreter list after refreshing (total 591ms, resolve 38ms, refresh 553ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
22:48:32.183 [debug] Full interpreter list after refreshing (total 4ms, resolve 3ms, refresh 1ms) is length: 4, /bin/python:undefined::/bin/python:/bin/python, /sbin/python:undefined::/sbin/python:/sbin/python, /usr/bin/python:undefined::/usr/bin/python:/usr/bin/python, /usr/sbin/python:undefined::/usr/sbin/python:/usr/sbin/python
22:48:32.194 [debug] refreshData after detecting changes to interpreters
22:48:32.195 [debug] Listing Python & non-Python kernels for Interpreter /bin/python
22:48:32.195 [debug] Listing Python & non-Python kernels for Interpreter /sbin/python
22:48:32.196 [debug] Finding Global Python KernelSpecs
22:48:32.201 [debug] refreshData after detecting changes to interpreters
22:48:32.201 [debug] Listing Python & non-Python kernels for Interpreter /usr/bin/python
22:48:32.203 [debug] refreshData after detecting changes to interpreters
22:48:32.204 [debug] Listing Python & non-Python kernels for Interpreter /usr/sbin/python
22:48:32.204 [debug] refreshData after detecting changes to interpreters
22:48:32.207 [debug] refreshData after detecting changes to interpreters
22:48:32.209 [debug] Full interpreter list is length: 4, /bin/python::Unknown:/bin/python, /sbin/python::Unknown:/sbin/python, /usr/bin/python::Unknown:/usr/bin/python, /usr/sbin/python::Unknown:/usr/sbin/python
22:48:32.209 [debug] Refreshed Environments
22:48:32.231 [debug] Kernel for interpreter /bin/python is .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:48:32.232 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:48:32.236 [debug] Kernel for interpreter /sbin/python is .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
22:48:32.236 [debug] Kernels for interpreter /sbin/python are .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
22:48:32.238 [debug] Kernel for interpreter /usr/bin/python is .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
22:48:32.238 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
22:48:32.241 [debug] Kernel for interpreter /usr/sbin/python is .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
22:48:32.241 [debug] Kernels for interpreter /usr/sbin/python are .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
22:48:32.279 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
22:48:32.279 [debug] start the kernel, options.disableUI=true for ~/study/python/lab/lab.ipynb
22:48:32.281 [debug] Initialize notebook communications for editor ~/study/python/lab/lab.ipynb
22:48:32.282 [debug] Resolving notebook UI Comms (resolve) for ~/study/python/lab/lab.ipynb
22:48:32.282 [debug] initialize CommonMessageCoordinator
22:48:32.288 [debug] Registering commtarget jupyter.widget
22:48:32.288 [debug] IPyWidgetMessageDispatcher.initialize
22:48:32.289 [debug] Attempting to determine version of IPyWidgets
22:48:32.290 [debug] Controller selection change completed
22:48:32.290 [debug] Waiting for IPyWidgets version
22:48:32.290 [debug] Waiting for IPyWidgets version promise
22:48:32.329 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher  (Python Path: /bin/python, Unknown, 3.10.10) for '~/study/python/lab/lab.ipynb' (disableUI=true)
22:48:32.329 [debug] Creating raw notebook for resource '~/study/python/lab/lab.ipynb'
22:48:32.331 [debug] Kernel Launcher. launch, Class name = Kg (started execution), Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
22:48:32.332 [debug] Getting activated env variables, Class name = Is (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:48:32.332 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
22:48:32.340 [debug] Get Custom Env Variables, Class name = wc, completed in 8ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "RunPythonCode"
22:48:32.362 [debug] Launching kernel in kernelProcess.ts, Class name = Ug (started execution), Arg 1: "~/study/python/lab", Arg 2: ""
22:48:32.445 [warn] Failed to get activated env vars for /bin/python in 112ms
22:48:32.445 [debug] Prepend PATH with user site path for /bin/python, user site ~/.local/bin
22:48:32.445 [debug] Prepend PATH with python bin for /bin/python, 
    PATH value is ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:48:32.445 [debug] Activated Env Variables for /bin/python, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl and 
    Path value is undefined
22:48:32.445 [debug] Got env vars with python /bin/python in 113ms with 46 variables
22:48:32.445 [debug] Getting activated env variables, Class name = Is, completed in 113ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: <Uri:/bin/python>, Arg 3: undefined
22:48:32.459 [info] Process Execution: /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:48:32.460 [debug] Kernel Env Variables for ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/jupyter/kernels/pythonjvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a/kernel.json, PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
22:48:32.484 [info] Process Execution: /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"fe8fecf9-1672-48cb-87d8-97eb11bf024d" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-616004Xu74T065wrRc.json
    > cwd: ~/study/python/lab
22:48:32.485 [debug] Launching kernel in kernelProcess.ts, Class name = Ug, completed in 123ms, has a truthy return value, Arg 1: "~/study/python/lab", Arg 2: ""
22:48:32.863 [info] ipykernel version & path 6.22.0, ~/.local/lib/python3.10/site-packages/ipykernel/__init__.py for /bin/python
22:48:33.209 [info] End refreshing Kernel Picker (1683488910951)
22:48:33.472 [debug] KernelProcess error: ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'fe8fecf9-1672-48cb-87d8-97eb11bf024d' instead of 'b"fe8fecf9-1672-48cb-87d8-97eb11bf024d"'.
  warn(

22:48:33.486 [debug] KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-616004Xu74T065wrRc.json

22:48:33.486 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-616004Xu74T065wrRc.json

22:48:33.523 [debug] Kernel Launcher. launch, Class name = Kg, completed in 1192ms, has a truthy return value, Arg 1: ".jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/study/python/lab/lab.ipynb", Arg 4: "~/study/python/lab", Arg 5: ""
22:48:33.532 [info] ZMQ loaded without the fallback mechanism.
22:48:33.538 [debug] Waiting for Raw Session to be ready in postStartRawSession
22:48:33.538 [debug] Waiting for Raw session to be ready, currently connected
22:48:33.538 [debug] Raw session connected
22:48:33.538 [debug] Waiting for Raw session to be ready for 30s
22:48:33.539 [debug] Waited for Raw session to be ready & got connected
22:48:33.539 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
22:48:33.539 [debug] Kernel status before requesting kernel info and after ready is unknown
22:48:33.539 [debug] Sending request for kernelinfo
22:48:33.545 [debug] Got response for requestKernelInfo
22:48:33.545 [debug] Successfully compelted postStartRawSession
22:48:33.546 [info] Started Kernel Python 3.10.10 (pid: 616172)
22:48:33.546 [info] Started new session fb971ee8-6875-41e2-a5cf-89d582bd02b9
22:48:33.547 [debug] Started running kernel initialization for ~/study/python/lab/lab.ipynb
22:48:33.548 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
22:48:33.635 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
22:48:33.635 [debug] Determined IPyKernel Version as 8 and event fired
22:48:33.635 [debug] Version of IPyWidgets 8 determined after 1.346s
22:48:33.640 [debug] Initialize matplotlib for ~/study/python/lab/lab.ipynb
22:48:33.641 [debug] Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD
22:48:34.193 [debug] IPyWidgetMessageDispatcher.initialize
22:48:34.193 [debug] Web view is ready to receive widget messages
22:48:34.223 [debug] Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/study/python/lab"\nif _VSCOD with 1 output(s)
22:48:34.223 [debug] Requesting Kernel info
22:48:34.224 [debug] Got Kernel info
22:48:34.224 [debug] End running kernel initialization, now waiting for idle
22:48:34.224 [debug] Waiting for 60000ms idle on (kernel): fb971ee8-6875-41e2-a5cf-89d582bd02b9 -> idle
22:48:34.224 [debug] Finished waiting for idle on (kernel): fb971ee8-6875-41e2-a5cf-89d582bd02b9 -> idle
22:48:34.224 [debug] End running kernel initialization, session is idle
22:48:34.226 [debug] IPyWidgetScriptSource.initialize
22:48:34.227 [debug] IPyWidgetMessageDispatcher.initialize
22:48:34.227 [debug] getDataDirsImpl, Class name = nh (started execution), Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
22:48:34.228 [debug] Get Custom Env Variables, Class name = wc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
22:48:34.229 [debug] Get Custom Env Variables, Class name = wc, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:48:34.229 [debug] Jupyter Paths : 
22:48:34.240 [info] Process Execution: /bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/pythonFiles/printJupyterDataDir.py
22:48:34.254 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
22:48:34.255 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
22:48:34.271 [debug] IPyWidgetMessageDispatcher.initialize
22:48:34.272 [debug] IPyWidgetMessageDispatcher.initialize
22:48:34.275 [debug] getDataDirsImpl, Class name = nh, completed in 48ms, has a truthy return value, Arg 1: "~/study/python/lab/lab.ipynb", Arg 2: "/bin/python"
22:48:34.299 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/temp/scripts/5025d6a5c4df71f4502a853d7f80a37d8be0228745293b0e528bc4850f83a169/jupyter
22:48:47.242 [debug] Updating cache with Python kernels startUsingPythonInterpreter:'.jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (interpreter id = /bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (interpreter id = /sbin/python)', startUsingPythonInterpreter:'.jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (interpreter id = /usr/bin/python)', startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Added = startUsingPythonInterpreter:'.jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (interpreter id = /usr/sbin/python)', Updated = , Removed = 
23:01:59.056 [info] Shutting down notebooks for f2aa33b5-70f1-433c-8aed-097b45cc4619
23:01:59.056 [info] Disposing HostJupyterExecution 9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.056 [debug] Disposing super HostJupyterExecution 9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.056 [info] Dispose Kernel '~/study/python/lab/lab.ipynb' associated with '~/study/python/lab/lab.ipynb'
23:01:59.057 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224370
	at jm.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:224579)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770348
	at Array.map (<anonymous>)
	at va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770338)
	at Module.FE (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:590356)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:10974)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
23:01:59.057 [debug] shutdownSession fb971ee8-6875-41e2-a5cf-89d582bd02b9, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
23:01:59.058 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
23:01:59.060 [info] Dispose Kernel process 616172.
23:01:59.074 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/study/python/lab/lab.ipynb
23:01:59.075 [info] Disposing HostJupyterExecution 9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.075 [debug] Finished disposing HostJupyterExecution  9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.078 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher and documents file://~/study/python/lab/lab.ipynb
23:01:59.078 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:01:59.079 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:01:59.081 [debug] Cleaning up server cache 9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.083 [debug] Shutdown session - current session, called from Error: 
	at ov.shutdownImplementation (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:168193)
	at ov.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:162652)
	at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121414
	at Array.map (<anonymous>)
	at av.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:121404)
	at async Promise.all (index 0)
	at async va.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:2:1770360)
	at async Promise.all (index 12)
	at async v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9171)
23:01:59.083 [debug] shutdownSession fb971ee8-6875-41e2-a5cf-89d582bd02b9, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - start
23:01:59.083 [debug] Session can be shutdown .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
23:01:59.084 [debug] Finished disposing HostJupyterExecution  9ed55460-1a33-439f-b4e2-60aa1de1294f
23:01:59.087 [debug] Disposed Kernel process 616172.
23:01:59.088 [debug] shutdownSession fb971ee8-6875-41e2-a5cf-89d582bd02b9, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
23:01:59.088 [debug] shutdownSession fb971ee8-6875-41e2-a5cf-89d582bd02b9, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher - shutdown complete
23:01:59.088 [debug] Shutdown session - get restart session
23:01:59.088 [debug] Shutdown session -- complete
23:01:59.089 [debug] Shutdown session - get restart session
23:01:59.089 [debug] Shutdown session -- complete
23:01:59.090 [warn] Failed to delete connection file ~/.local/share/jupyter/runtime/kernel-v2-616004Xu74T065wrRc.json for pid 616172 [Canceled (FileSystemError): Canceled
	at Zt.c (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:27273)
	at Object.stat (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:100:25374)
	at async _d.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:17:18527)
	at async ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.4.1001091014-universal/out/extension.node.js:24:89152] {
  code: 'Unknown'
}
23:01:59.094 [debug] KernelProcess Exit Exit - undefined ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'fe8fecf9-1672-48cb-87d8-97eb11bf024d' instead of 'b"fe8fecf9-1672-48cb-87d8-97eb11bf024d"'.
  warn(

